Select * from SRC_SCRIPTS_CONFIG;
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (1,'extraction_batch','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (2,'product_ex','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (3,'company_ex','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (4,'customer_ex','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (5,'price_ex','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (6,'order_ex','1','F');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (7,'order_delta_ex','1','D');
INSERT INTO SRC_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (8,'web_log_ex','1','F');