INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (1,'load_batch','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (2,'product_ld','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (3,'company_ld','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (4,'customer_ld','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (5,'price_ld','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (6,'order_ld','1','F');
INSERT INTO DWH_SCRIPTS_CONFIG (JOB_ID, JOB_NAME, JOB_FREQUENCY, LOAD_TYPE)
VALUES (7,'web_log_ld','1','F');
