--User Setup

CREATE OR REPLACE USER BATCH_USER PASSWORD = 'P@ssw0rd123' LOGIN_NAME = 'BATCH_USER' DISPLAY_NAME = 'Batch' FIRST_NAME = 'Batch' LAST_NAME = 'User' DEFAULT_ROLE = "DWH_BATCH" MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE "PUBLIC" TO USER BATCH_USER;
GRANT ROLE "DWH_BATCH" TO USER BATCH_USER;
GRANT ROLE "DWH_REPORT" TO USER BATCH_USER;

CREATE USER DWH_USER PASSWORD = 'P@ssw0rd123' LOGIN_NAME = 'DWH_USER' DISPLAY_NAME = 'DWH' FIRST_NAME = 'DataMart' LAST_NAME = 'User' DEFAULT_ROLE = "DWH_USER" MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE "PUBLIC" TO USER DWH_USER;
GRANT ROLE "DWH_USER" TO USER DWH_USER;
GRANT ROLE "DWH_REPORT" TO USER DWH_USER;


CREATE OR REPLACE USER REPORTUSER PASSWORD = 'P@ssw0rd123' LOGIN_NAME = 'REPORTUSER' DISPLAY_NAME = 'Reporting User' FIRST_NAME = '' LAST_NAME = ''  DEFAULT_ROLE = "DWH_REPORT";
GRANT ROLE "DWH_REPORT" TO USER REPORTUSER;

GRANT ROLE "DWH_REPORT" TO USER ARUNBASNET;