create or replace schema SOURCE;

create or replace TABLE COMPANY (
	CU_ID NUMBER(38,0) autoincrement,
	NAME VARCHAR(16777216),
	SUPPLIER_FLAG VARCHAR(16777216),
	LOGIN_NAME VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	LOCATION VARCHAR(16777216),
	constraint PK_COMPANY primary key (CU_ID)
);
create or replace TABLE CUSTOMER (
	DO_ID NUMBER(38,0) autoincrement,
	FIRST_NAME VARCHAR(16777216),
	FULL_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	DOB DATE,
	LOGIN_NAME VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	LOCATION VARCHAR(16777216),
	constraint PK_CUSTOMER primary key (DO_ID)
);
create or replace TABLE ORDERS (
	ORDER_NUM NUMBER(38,0) autoincrement,
	PARENT_ORDER_NUM NUMBER(38,0),
	ORDER_TYPE VARCHAR(16777216),
	BUYER NUMBER(38,0),
	SELLER NUMBER(38,0),
	PROD_ID NUMBER(38,0),
	ORDERED_BY NUMBER(38,0),
	QTY FLOAT,
	UNIT_PRICE FLOAT,
	TOTAL_AMOUNT FLOAT,
	ORDER_DATE DATE,
	SHIPPING_ADDRESS VARCHAR(16777216),
	DELIVERY_CONTACT VARCHAR(16777216),
	DELIVERY_STATUS VARCHAR(16777216),
	DELIVERED_DATE DATE,
	LAST_UPDATE_DT DATE,
	constraint PK_ORDER primary key (ORDER_NUM)
);

create or replace TABLE PRICE (
	ROW_ID NUMBER(38,0) autoincrement,
	CU_ID NUMBER(38,0),
	PROD_ID NUMBER(38,0),
	UNIT_PRICE FLOAT,
	SUPPLIER_FLAG VARCHAR(1),
	constraint PK_PRICE primary key (CU_ID, PROD_ID)
);
create or replace TABLE PRODUCT (
	PROD_ID NUMBER(38,0) autoincrement,
	DESCRIPTION VARCHAR(16777216),
	DEPARTMENT VARCHAR(16777216),
	CLASS VARCHAR(16777216),
	constraint PK_PRODUCT primary key (PROD_ID)
);
create or replace TABLE SRC_BATCH_LOG (
	BATCH_ID NUMBER(10,0),
	JOB_ID NUMBER(10,0),
	JOB_NAME VARCHAR(50),
	RUN_DATE DATE,
	STRT_TMS TIMESTAMP_NTZ(9),
	END_TMS TIMESTAMP_NTZ(9),
	STATUS VARCHAR(20),
	ERROR_MESSAGE VARCHAR(100),
	BOOKMARK VARCHAR(100),
	LOGFILE VARCHAR(100)
);
create or replace TABLE SRC_SCRIPTS_CONFIG (
	JOB_ID NUMBER(10,0) NOT NULL,
	JOB_NAME VARCHAR(100),
	JOB_FREQUENCY VARCHAR(20),
	LOAD_TYPE VARCHAR(1),
	constraint PK_SRC_SCRIPTS_CONFIG primary key (JOB_ID)
);

CREATE OR REPLACE FILE FORMAT ETL
	TYPE = csv
	FIELD_DELIMITER = '|'
	FIELD_OPTIONALLY_ENCLOSED_BY = ''''
	NULL_IF = ('NULL')
;
