create or replace schema DWH_REPORT;

create or replace view DWH_V_DEVICES_USUAGE_F(
	USED_DEVICE,
	LOGIN_COUNT
) as
Select TOP 5 NVL(SPLIT_PART(SPLIT_PART(agent,'(',2),')',1),'Unknown') USED_DEVICE, count(NVL(SPLIT_PART(SPLIT_PART(agent,'(',2),')',1),'Unknown')) LOGIN_COUNT
from TARGET.DWH_WEB_LOG_DATA

group by (NVL(SPLIT_PART(SPLIT_PART(agent,'(',2),')',1),'Unknown'))
order by LOGIN_COUNT desc;
create or replace view DWH_V_MONTHLY_SALES_LY_F(
	MONTH_END_DATE,
	MONTH_KY,
	MONTH,
	MONTHLY_SALES_IN_MILLION
) as
Select MONTH_END_DATE, Month_kY, YEAR_KY||' '||MONTH_DESC MONTH, TO_NUMBER(SUM(TOTAL_AMOUNT)/1000000,10,2) MONTHLY_SALES_in_million  from TARGET.DWH_ORDERS_F sales,TARGET.DWH_TIME_DAY_D DATE where sales.ORDER_DATE=DATE.ID
and DELIVERY_STATUS='Delivered'
AND YEAR_KY = YEAR(DATEADD(YEAR,-1,CURRENT_DATE))
group by YEAR_KY||' '||MONTH_DESC,MONTH_END_DATE,  Month_kY order by Month_kY asc;
create or replace view DWH_V_POPULAR_PRODUCT_F(
	PROD_ID,
	DESCRIPTION,
	TOTAL_SALES_INMILLION
) as
Select PROD.PROD_ID, PROD.DESCRIPTION , TO_NUMBER(SUM(TOTAL_AMOUNT)/1000000,38,2) TOTAL_SALES_inMillion from
TARGET.DWH_ORDERS_F SRC LEFT JOIN TARGET.DWH_PRODUCT_D PROD ON (SRC.PROD_ID = PROD.PROD_ID)
LEFT JOIN TARGET.DWH_COMPANY_D COMP_BUYER ON (
		SRC.BUYER = COMP_BUYER.CU_ID
		AND SRC.ORDER_TYPE LIKE 'COMPANY_PO'
		)
LEFT JOIN TARGET.DWH_CUSTOMER_D CUST_BUYER ON (
		SRC.BUYER = CUST_BUYER.DO_ID
		AND SRC.ORDER_TYPE LIKE 'COMPANY_SALES'
		)
LEFT JOIN TARGET.DWH_COMPANY_D COMP_SELLER ON (SRC.SELLER = COMP_SELLER.CU_ID)
INNER JOIN
(Select  TOP 1
COUNTRY
from TARGET.DWH_WEB_LOG_DATA LOG_IN, (SELECT LOGIN_NAME , COUNTRY from TARGET.DWH_COMPANY_D  UNION ALL SELECT LOGIN_NAME , COUNTRY from  TARGET.DWH_CUSTOMER_D CUST) COMP
where LOG_IN.USERNAME=COMP.LOGIN_NAME
group by COMP.COUNTRY
order by count(*) desc) TOP_COUNTRY on COALESCE(COMP_BUYER.COUNTRY,CUST_BUYER.COUNTRY,COMP_SELLER.COUNTRY)=TOP_COUNTRY.COUNTRY
where DELIVERY_STATUS='Delivered'
group by PROD.PROD_ID, PROD.DESCRIPTION ;